# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Mister Market Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  IEX_TOKEN: ${{ secrets.IEX_TEST_TOKEN }} 
  IEX_API_VERSION: ${{ secrets.IEX_TEST_API_VERSION }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        set -xe
        python -VV
        python -m site
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tox target 
      run: |
        tox -v
